#!/usr/bin/env ruby

#make sure to install roo-xls gem install roo roo-xls

require "rubygems"
require "roo-xls"
require "shellwords"
require "pathname"
require "csv"

extract = ARGV.first

RUBYOPT="-rrestore_environment"
CSV.open("#{Dir.pwd}/#{extract}.csv", "wb") do |csv|
  csv << (2006...2016).to_a.reverse.map{|x|"Year #{x}"}.unshift("Name of Company")
  Dir.foreach("#{Dir.pwd}/downloaded_data").drop(2).each do |file|
    xls = Roo::Excel.new("#{Dir.pwd}/downloaded_data/#{file.gsub(/ /, '\ ')}")
    company_name =  xls.to_csv.lines.first.gsub(',', '').gsub('"', '')

    row = xls.to_csv.lines.select{|x| /#{extract}"/ =~ x}.map{|x|x.scan(/\d+/)}.flatten.unshift(company_name)

    csv << row
  end
end
